// Validates the data, embeds any logos from /logos, and inlines everything into
// defense-tech-map.html (a standalone page) plus dist/defense-tech-map.artifact.html
// (the same page as a body fragment for publishing as a claude.ai Artifact).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadData, validate } from './validate.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const src = (p) => path.join(root, 'src', p);

// 1. Logos: logos/<company-id>.(svg|png|jpg|webp). Add ".dark" before the extension
//    (e.g. anduril.dark.svg) for a white mark that should sit on the dark logo square.
const MIME = { svg: 'image/svg+xml', png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', webp: 'image/webp' };
const logoDir = path.join(root, 'logos');
const logos = {};
if (fs.existsSync(logoDir)) {
  for (const f of fs.readdirSync(logoDir).sort()) {
    const m = f.match(/^([a-z0-9-]+?)(\.dark)?\.(svg|png|jpe?g|webp)$/);
    if (!m) continue;
    const buf = fs.readFileSync(path.join(logoDir, f));
    logos[m[1]] = { src: `data:${MIME[m[3]]};base64,${buf.toString('base64')}`, dark: !!m[2] };
  }
}
fs.writeFileSync(src('data/logos.js'),
  `/* Generated by scripts/build.mjs from /logos. Do not edit by hand. */\nDTM.logos = ${JSON.stringify(logos, null, 0)};\n`);

// 2. Validate.
const D = loadData();
const { errors, warnings } = validate(D);
if (errors.length) {
  console.error(`Data has ${errors.length} error(s):`);
  errors.forEach((e) => console.error('  ' + e));
  process.exit(1);
}

// 3. Inline CSS and scripts.
let html = fs.readFileSync(src('index.html'), 'utf8');
const safe = (s) => s.replace(/<\/(script|style)/gi, '<\\/$1');
html = html.replace(/<link rel="stylesheet" href="styles\.css">/, () => `<style>\n${safe(fs.readFileSync(src('styles.css'), 'utf8'))}\n</style>`);
html = html.replace(/<script src="([^":]+)"><\/script>/g, (_, rel) => {
  const file = src(rel);
  if (!fs.existsSync(file)) return '';
  return `<script>/* ${rel} */\n${safe(fs.readFileSync(file, 'utf8'))}\n</script>`;
});
const stamp = `<!-- Built ${new Date().toISOString().slice(0, 10)} from src/ by scripts/build.mjs. Edit the source files, then run npm run build. -->\n`;
const full = html.replace(/<!doctype html>\n/i, (m) => m + stamp);
fs.writeFileSync(path.join(root, 'defense-tech-map.html'), full);

// 4. Artifact fragment: no document skeleton, and no remote favicon requests (the CSP blocks them).
const fragment = html
  .replace(/<!doctype html>\s*/i, '')
  .replace(/<html[^>]*>\s*/i, '')
  .replace(/<\/html>\s*/i, '')
  .replace(/<head>\s*/i, '')
  .replace(/<\/head>\s*/i, '')
  .replace(/<body>\s*/i, '')
  .replace(/<\/body>\s*/i, '')
  .replace(/<meta charset="utf-8">\s*/i, '')
  .replace(/<meta name="viewport"[^>]*>\s*/i, '')
  .replace(/<script>\/\* data\/taxonomy\.js \*\//, '<script>window.DTM_REMOTE_LOGOS = false;</script>\n$&');
fs.mkdirSync(path.join(root, 'dist'), { recursive: true });
fs.writeFileSync(path.join(root, 'dist/defense-tech-map.artifact.html'), fragment);

const kb = (s) => (Buffer.byteLength(s) / 1024).toFixed(0) + ' KB';
console.log(`Built defense-tech-map.html (${kb(full)}) and dist/defense-tech-map.artifact.html (${kb(fragment)})`);
console.log(`${D.companies.length} companies, ${Object.keys(logos).length} embedded logos, ${warnings.length} data warnings (npm run validate -- --verbose)`);
